;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/ProjectSneak/Data/Tables/DT_PSGameplayTags.DT_PSGameplayTags
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Shield",DevComment="")
+GameplayTagList=(Tag="Data.SpeedMultiplier",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Damaged",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SpeedChanged",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SpeedDown",DevComment="")
+GameplayTagList=(Tag="GameplayCue.SpeedUp",DevComment="")
+GameplayTagList=(Tag="State.Stun",DevComment="")

